### ISSUE TITLE
知乎账号的Cookie哪里看？

### ISSUE THREAD

**Issue by Song-s-z** [skyIsland/Sky.Zhihu.Crawler#1]
> Cookie:顾名思义,就是你知乎账号的Cookie了

这个cookie的值是ttps://www.zhihu.com/api/v4/questions/46508954/answers?时， 按F12从request header里看到的那个cookie么？ 我的是类似于下面这种，和你的差别怎么这么大呢？

> cookie:_zap=bb597634-86d0-4636-a516-89e76b4b5335; __utmz=155987696.1514271927.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); l_cap_id="ZjJmNjAzMDMzZjg0NDc1ODg4NGJhOTdiMmE2NmJlNGM=|1514275114|e5b925756a5fce209d482547e90e126b9eccab15"; r_cap_id="NGVhNDAxZmYyZDBmNGFlN2JiN2U4ZTkyZGE4NmY3MTc=|1514275114|06035e0654b5ed7578d7cf4ce4e5dc24e855e688"; cap_id="M2VjMmQzNWE4MDVhNDMwODg4NTJiYTg4YjgxZDY4MWM=|1514275114|d870eba27da9944828effdae82ccc2c566f43348"; __utma=155987696.1051667396.1514271927.1514271927.1514276496.2; q_c1=b2e3af8dde034209a6948fcd9fd0e70f|1515131469000|1509512040000; d_c0="AJBrsuC5AA2PTqu9qOLgytIZlpXzmzgRgcE=|1516167026"; _xsrf=ec351d2e-f0b2-4b2e-9eff-a3262a9faf10; capsion_ticket="2|1:0|10:1516261057|14:capsion_ticket|44:NzU1ZGRjYTA3Y2U3NGVjZWE4MWIzMzllNjA1NjMxZGQ=|b73bb13fe6a623db85478f5eb46ed51906674b89f29e4ef1a067fce6dcd90f54"; z_c0="2|1:0|10:1516261068|4:z_c0|92:Mi4xMzMwVEFBQUFBQUFBa0d1eTRMa0FEU1lBQUFCZ0FsVk56SnhOV3dETFF5VGlla1ZDUllwcUVMRVhMWk4wV1duOVJn|f2fcc1750b966a19dd202ddc2eb42dca9dc9f573421bc3a8675a072e603ca897"

**Comment by skyIsland** [comment]
你好,最后三行cookie才是关键的,z_c0那一段

**Comment by skyIsland** [comment]
全部复制进去也可以。

**Comment by Song-s-z** [comment]
你好，我尝试过全复制进去，也试过只复制最后三行，一直都是异常“The remote server returned an error: (401) Unauthorized.”你有遇到过这种情况吗？

**Comment by skyIsland** [comment]
#### 你怎么复制的?401应该就是cookie没复制对.
#### 另,我刚刚试了,还是可以下载图片的.
> 刚刚下载的
![image](http://p1oh6lrck.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180119135946.png)
![image](http://p1oh6lrck.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20180119140427.png)

**Comment by Song-s-z** [comment]
我用的是chrome，先到https://www.zhihu.com/question/46508954，
按F12，复制第一个url下面的cookie，然后复制到setting.json:
"Cookie": "2|1:0|10:1516261068|4:z_c0|92:Mi4xMzMwVEFBQUFBQUFBa0d1eTRMa0FEU1lBQUFCZ0FsVk56SnhOV3dETFF5VGlla1ZDUllwcUVMRVhMWk4wV1duOVJn|f2fcc1750b966a19dd202ddc2eb42dca9dc9f573421bc3a8675a072e603ca897",

其他的代码没有改动。

   #
![error](https://user-images.githubusercontent.com/5573534/35137635-5bf6801c-fd25-11e7-9d60-2b10bfb976f0.png)

**Comment by skyIsland** [comment]
少了'zc0='

**Comment by Song-s-z** [comment]
真是好奇怪，我现在setting.json:

>  "Cookie": "z_c0=2|1:0|10:1516261068|4:z_c0|92:Mi4xMzMwVEFBQUFBQUFBa0d1eTRMa0FEU1lBQUFCZ0FsVk56SnhOV3dETFF5VGlla1ZDUllwcUVMRVhMWk4wV1duOVJn|f2fcc1750b966a19dd202ddc2eb42dca9dc9f573421bc3a8675a072e603ca897",
 
还是跟刚才一样爆401，是不是header里面还会有影响到的设置？

**Comment by skyIsland** [comment]
#### ……你项目文件是怎么样的

**Comment by Song-s-z** [comment]
![error](https://user-images.githubusercontent.com/5573534/35140903-df35716e-fd33-11e7-8cd4-65bc86c741d0.png)

**Comment by skyIsland** [comment]
你该外层文件夹Bin里面的setting. json试试

**Comment by Song-s-z** [comment]
项目文件是指.proj吗？ 应该没动过。。。

**Comment by Song-s-z** [comment]
完美啊，工作了，原来访问的是这个setting.json, 谢谢你的解释 :）

**Comment by skyIsland** [comment]
回头我把项目里的setting. json删掉，以免造成误会。
